# Generated by Django 3.0.8 on 2020-07-30 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_baseuser_archived'),
        ('clinics', '0002_auto_20200728_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('information', models.TextField()),
                ('status', models.CharField(choices=[('IN PROGRESS', 'In progress'), ('DONE', 'Done'), ('DECLINED', 'Declined'), ('WAITING', 'Waiting')], default='WAITING', max_length=20)),
                ('answer', models.TextField(blank=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='users.Ailing')),
                ('to_clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='clinics.Clinic')),
            ],
        ),
    ]
