# Generated by Django 3.0.8 on 2020-07-28 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0009_add_subregion'),
        ('users', '0002_auto_20200726_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ailing',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(max_length=200)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ailings', to='cities_light.City')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.baseuser',),
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
    ]
