# Generated by Django 3.0.8 on 2020-07-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_ailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
